import "./globals.css";
import Script from "next/script";
import * as snippet from "@segment/snippet";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function renderSnippet() {
  const opts = {
    apiKey: process.env.NEXT_PUBLIC_ANALYTICS_WRITE_KEY,
    page: true,
  };

  return snippet.max(opts);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="container mx-auto h-[100vh] w-[100vw]">
          {children}
        </main>
        <Script
          id="segment-script"
          dangerouslySetInnerHTML={{ __html: renderSnippet() }}
        />
      </body>
    </html>
  );
}
