import "./globals.css";
import Script from "next/script";
import * as segment from "@segment/snippet";
import { Header } from "@/components/ui/header";

export const metadata = {
  title: "next-amplify-beta-routing",
  description: "Generated by create next app",
};

function renderSnippet() {
  const opts = {
    apiKey: process.env.NEXT_PUBLIC_ANALYTICS_WRITE_KEY,
    page: true,
  };

  // when using in real project it's better not to use max in DEV mode
  return segment.max(opts);
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="container mx-auto h-[100vh] w-[100vw]">
          {children}
        </main>
        <Script
          id="segment-script"
          dangerouslySetInnerHTML={{ __html: renderSnippet() }}
        />
      </body>
    </html>
  );
}
